services:
  postgres:
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql
    image: postgres
  pgadmin4:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - ./pgadmin:/var/lib/pgadmin:rw
    user: "${UID}:${GID}"