services:
  postgres:
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - /home/user1/Documents/GitHub/docker/postgres:/var/lib/postgresql
    networks:
      - home
    image: postgres
networks:
  home: {}
